@ -1,11 +0,0 @@
﻿services:
  - type: web
    name: mi-api-email
    runtime: python
    repo: https://github.com/niwellcuello-lang/mi-api-email
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app

